
from utils import *


CONFIG_FILE_NAME = 'mouse-free.config'

properties = get_config_from_properties_file(CONFIG_FILE_NAME)

# hotkey
KEYBOARD_SHOW_HOTKEY = properties['KEYBOARD_SHOW_HOTKEY']
KEYBOARD_SHOW_DETAIL_HOTKEY = properties['KEYBOARD_SHOW_DETAIL_HOTKEY']
KEYBOARD_SHOW_IN_SWITCHED_SCREEN_HOTKEY = properties['KEYBOARD_SHOW_IN_SWITCHED_SCREEN_HOTKEY']
KEYBOARD_HIDE_HOTKEY = properties['KEYBOARD_HIDE_HOTKEY']
KEYBOARD_QUIT_HOTKEY = properties['KEYBOARD_QUIT_HOTKEY']
KEYBOARD_MOUSE_CLICK_LEFT_HOTKEY = properties['KEYBOARD_MOUSE_CLICK_LEFT_HOTKEY']
KEYBOARD_MOUSE_CLICK_LEFT_DOUBLE_HOTKEY = properties['KEYBOARD_MOUSE_CLICK_LEFT_DOUBLE_HOTKEY']
KEYBOARD_MOUSE_CLICK_RIGHT_HOTKEY = properties['KEYBOARD_MOUSE_CLICK_RIGHT_HOTKEY']

# log file path
LOG_FILE_PATH = properties['LOG_FILE_PATH']
# log level
LOG_LEVEL = str_to_log_level(str(properties['LOG_LEVEL']).strip().upper())


# screen
# fixed configuration
MAX_CELL_LEVEL = 2 # max level， start from 1

# customizable configuration
TRANSPARENCY = 50  # N / 100
DELAY_HIDE_TIME = 5 # second
BACKGROUND_COLOR = (173, 216, 230) 
IDENTIFIER_FONT_COLOR = (0, 0, 0)
THREAD_POOL_MAX_WORKERS = 5 

# customizable configuration
CELL_WIDTH_COLUMN_SIZE = 75  # level 1 cell width
CELL_HEIGHT_ROW_SIZE = 45  # level 1 cell height
FONT_SIZE = 12  # level 1 font size
# fixed configuration
IDENTIFIER_KEY_COUNT = 2

# customizable configuration
CELL_WIDTH_COLUMN_SIZE_LEVEL2 = 12 # level 2 cell width
CELL_HEIGHT_ROW_SIZE_LEVEL2 = 12 # level 2 cell height
FONT_SIZE_LEVEL2 = 8 # level 2 font size
# fixed configuration
IDENTIFIER_KEY_COUNT_LEVEL2 = 1
CELL_COUNT_PER_WIDTH_PER_HEIGHT_LEVEL2 = 5
SCREEN_WIDTH_COLUMN_SIZE_LEVEL2 = CELL_WIDTH_COLUMN_SIZE_LEVEL2 * CELL_COUNT_PER_WIDTH_PER_HEIGHT_LEVEL2
SCREEN_HEIGHT_ROW_SIZE_LEVEL2 = CELL_HEIGHT_ROW_SIZE_LEVEL2 * CELL_COUNT_PER_WIDTH_PER_HEIGHT_LEVEL2


# constant
LEVEL_1 = "LEVEL_1"
LEVEL_2 = "LEVEL_2"
LEVEL_DEFAULT = LEVEL_1

KEY_CELL_WIDTH_COLUMN_SIZE = "CELL_WIDTH_COLUMN_SIZE"
KEY_CELL_HEIGHT_ROW_SIZE = "CELL_HEIGHT_ROW_SIZE"
KEY_FONT_SIZE = "FONT_SIZE"
KEY_SCREEN_WIDTH_COLUMN_SIZE = "SCREEN_WIDTH_COLUMN_SIZE"
KEY_SCREEN_HEIGHT_ROW_SIZE = "SCREEN_HEIGHT_ROW_SIZE"
KEY_IDENTIFIER_KEY_COUNT = "IDENTIFIER_KEY_COUNT"

APP_TITLE = 'Mouse-Free-Application'
